# Site settings
title: Preet's Blog
description: Journalist.CusineEnthusaist.Photographer.
keywords: Modern, Blogging, Fun
author: Preet Gulati
baseurl: "" # the subpath of your site, e.g. /blog/
url: "preetmaya.github.io" # the base hostname & protocol for your site
